# ===========
# CONFIG FILE
# ===========
#
# data
data: /home/nicola/data/electron/images/training.tif
labels: /home/nicola/data/electron/labels_01/training.tif
train_val_test_split: 0.08,1
split_orientation: z
type: tif3d
# network
input_size: 256,256
in_channels: 1
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: mse
lr: 0.001
epochs: 10
train_batch_size: 4
test_batch_size: 4
# compute
gpus: 0
num_workers: 6
accelerator: dp
# logging
log_dir: unet_2d
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
